services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: integracao-subadq-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - integracao-subadq-network
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: integracao-subadq-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - integracao-subadq-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: integracao-subadq-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: integracao_subadq
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: integracao
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - integracao-subadq-network

  redis:
    image: redis:7-alpine
    container_name: integracao-subadq-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - integracao-subadq-network

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: integracao-subadq-queue
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    command: php artisan queue:work redis --tries=3 --timeout=90 --sleep=3
    networks:
      - integracao-subadq-network
    depends_on:
      - db
      - redis
      - app

networks:
  integracao-subadq-network:
    driver: bridge

volumes:
  db_data:
    driver: local
